/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeditarRouteImport } from './routes/meditar'
import { Route as VisualizarRouteImport } from './routes/visualizar'
import { Route as ManifestarIndexRouteImport } from './routes/manifestar.index'
import { Route as ManifestarGoalRouteImport } from './routes/manifestar.$goal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditarRoute = MeditarRouteImport.update({
  id: '/meditar',
  path: '/meditar',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizarRoute = VisualizarRouteImport.update({
  id: '/visualizar',
  path: '/visualizar',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestarIndexRoute = ManifestarIndexRouteImport.update({
  id: '/manifestar/',
  path: '/manifestar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestarGoalRoute = ManifestarGoalRouteImport.update({
  id: '/manifestar/$goal',
  path: '/manifestar/$goal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diario': typeof DiarioRoute
  '/login': typeof LoginRoute
  '/meditar': typeof MeditarRoute
  '/visualizar': typeof VisualizarRoute
  '/manifestar/$goal': typeof ManifestarGoalRoute
  '/manifestar/': typeof ManifestarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diario': typeof DiarioRoute
  '/login': typeof LoginRoute
  '/meditar': typeof MeditarRoute
  '/visualizar': typeof VisualizarRoute
  '/manifestar/$goal': typeof ManifestarGoalRoute
  '/manifestar': typeof ManifestarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/diario': typeof DiarioRoute
  '/login': typeof LoginRoute
  '/meditar': typeof MeditarRoute
  '/visualizar': typeof VisualizarRoute
  '/manifestar/$goal': typeof ManifestarGoalRoute
  '/manifestar/': typeof ManifestarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/diario'
    | '/login'
    | '/meditar'
    | '/visualizar'
    | '/manifestar/$goal'
    | '/manifestar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/diario'
    | '/login'
    | '/meditar'
    | '/visualizar'
    | '/manifestar/$goal'
    | '/manifestar'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/diario'
    | '/login'
    | '/meditar'
    | '/visualizar'
    | '/manifestar/$goal'
    | '/manifestar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DiarioRoute: typeof DiarioRoute
  LoginRoute: typeof LoginRoute
  MeditarRoute: typeof MeditarRoute
  VisualizarRoute: typeof VisualizarRoute
  ManifestarGoalRoute: typeof ManifestarGoalRoute
  ManifestarIndexRoute: typeof ManifestarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditar': {
      id: '/meditar'
      path: '/meditar'
      fullPath: '/meditar'
      preLoaderRoute: typeof MeditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizar': {
      id: '/visualizar'
      path: '/visualizar'
      fullPath: '/visualizar'
      preLoaderRoute: typeof VisualizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifestar/': {
      id: '/manifestar/'
      path: '/manifestar'
      fullPath: '/manifestar/'
      preLoaderRoute: typeof ManifestarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifestar/$goal': {
      id: '/manifestar/$goal'
      path: '/manifestar/$goal'
      fullPath: '/manifestar/$goal'
      preLoaderRoute: typeof ManifestarGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DiarioRoute: DiarioRoute,
  LoginRoute: LoginRoute,
  MeditarRoute: MeditarRoute,
  VisualizarRoute: VisualizarRoute,
  ManifestarGoalRoute: ManifestarGoalRoute,
  ManifestarIndexRoute: ManifestarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
